copyright = "© 2025 Ali Rodrigo"
baseURL = "https://alirodrigo.com/"
languageCode = "en-us"
title = "Ali Rodrigo"
theme = "hugo-theme-gallery"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  description = "Galería de fotografías de Ali Rodrigo"
  title = "Projects"
  copyright = "© 2025 Ali Rodrigo"
  [params.author]
    email = "yo@alirodrigo.com"
    name = "Ali Rodrigo"
  [params.socialIcons]
    instagram = "https://www.instagram.com/alirodrigo_"
    github = "https://github.com/ali-rodrigo"
    youtube = "https://www.youtube.com/@alimalsoul"
    email = "mailto:yo@alirodrigo.com"
    #website = "https://alirodrigo.com"
    twitter = "https://x.com/alimalsoul"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[menu]
  [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "galeria"
    name = "galeria"
    url = "/gallery/"
    weight = 2

  [[menu.main]]
    identifier = "shop"
    name = "shop"
    url = "/shop/"
    weight = 3