baseURL = "https://ali-rodrigo.github.io/projects/"
languageCode = "es"
title = "Ali Rodrigo"
theme = "hugo-theme-gallery"

[params]
  description = "Galería de fotografías de Ali Rodrigo"
  copyright = "© 2025 Ali Rodrigo"